name: purpa_messenger
description: Android-first realtime messenger.
publish_to: 'none'
version: 0.8.7+31
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
  dio: ^5.9.0
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.0
  intl: ^0.20.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^15.2.10
  firebase_core: ^3.15.2
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
